# Generated by Django 6.1 on 2026-08-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_link', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('LINK_GENERATED', 'Link Generated'), ('MARKED_SENT', 'Marked Sent'), ('FAILED', 'Failed')], default='LINK_GENERATED', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='guests.guest')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='invitations.invitation')),
            ],
            options={
                'db_table': 'whatsapp_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
